title: 代码管理规范
description: 代码管理、版权、版本
themeConfig:
  nav:
  - text: git
    link: /git/
  - text: workflow
    link: /git-workflow/
  - text: monorepo
    link: /monorepo/
  - text: multirepo
    link: /multirepo/
  - text: 参与者公约
    link: 'https://www.contributor-covenant.org/zh-cn/version/1/4/code-of-conduct/'

  sidebar:
    /git/:
      - Tag
      - CHANGE_LOGO